 require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to test the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator. If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails. There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.

RSpec.describe "/merch_links", type: :request do
  
  # MerchLink. As you add validations to MerchLink, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    skip("Add a hash of attributes valid for your model")
  }

  let(:invalid_attributes) {
    skip("Add a hash of attributes invalid for your model")
  }

  describe "GET /index" do
    it "renders a successful response" do
      MerchLink.create! valid_attributes
      get merch_links_url
      expect(response).to be_successful
    end
  end

  describe "GET /show" do
    it "renders a successful response" do
      merch_link = MerchLink.create! valid_attributes
      get merch_link_url(merch_link)
      expect(response).to be_successful
    end
  end

  describe "GET /new" do
    it "renders a successful response" do
      get new_merch_link_url
      expect(response).to be_successful
    end
  end

  describe "GET /edit" do
    it "render a successful response" do
      merch_link = MerchLink.create! valid_attributes
      get edit_merch_link_url(merch_link)
      expect(response).to be_successful
    end
  end

  describe "POST /create" do
    context "with valid parameters" do
      it "creates a new MerchLink" do
        expect {
          post merch_links_url, params: { merch_link: valid_attributes }
        }.to change(MerchLink, :count).by(1)
      end

      it "redirects to the created merch_link" do
        post merch_links_url, params: { merch_link: valid_attributes }
        expect(response).to redirect_to(merch_link_url(MerchLink.last))
      end
    end

    context "with invalid parameters" do
      it "does not create a new MerchLink" do
        expect {
          post merch_links_url, params: { merch_link: invalid_attributes }
        }.to change(MerchLink, :count).by(0)
      end

      it "renders a successful response (i.e. to display the 'new' template)" do
        post merch_links_url, params: { merch_link: invalid_attributes }
        expect(response).to be_successful
      end
    end
  end

  describe "PATCH /update" do
    context "with valid parameters" do
      let(:new_attributes) {
        skip("Add a hash of attributes valid for your model")
      }

      it "updates the requested merch_link" do
        merch_link = MerchLink.create! valid_attributes
        patch merch_link_url(merch_link), params: { merch_link: new_attributes }
        merch_link.reload
        skip("Add assertions for updated state")
      end

      it "redirects to the merch_link" do
        merch_link = MerchLink.create! valid_attributes
        patch merch_link_url(merch_link), params: { merch_link: new_attributes }
        merch_link.reload
        expect(response).to redirect_to(merch_link_url(merch_link))
      end
    end

    context "with invalid parameters" do
      it "renders a successful response (i.e. to display the 'edit' template)" do
        merch_link = MerchLink.create! valid_attributes
        patch merch_link_url(merch_link), params: { merch_link: invalid_attributes }
        expect(response).to be_successful
      end
    end
  end

  describe "DELETE /destroy" do
    it "destroys the requested merch_link" do
      merch_link = MerchLink.create! valid_attributes
      expect {
        delete merch_link_url(merch_link)
      }.to change(MerchLink, :count).by(-1)
    end

    it "redirects to the merch_links list" do
      merch_link = MerchLink.create! valid_attributes
      delete merch_link_url(merch_link)
      expect(response).to redirect_to(merch_links_url)
    end
  end
end
